name: Trigger auto deployment for comp7940

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/comp7940-AutoDeployTrigger-3a22d563-8b9b-4567-b920-a661db8b9df9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COMP7940_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COMP7940_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COMP7940_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 24428078images.azurecr.io
          registryUsername: ${{ secrets.COMP7940_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COMP7940_REGISTRY_PASSWORD }}
          containerAppName: comp7940
          resourceGroup: 24428078
          imageToBuild: 24428078images.azurecr.io/comp7940:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


